# ******************************************************************************
# This file will not enable the deployment of Ceph in future releases.
# Use ./ceph-ansible/ceph-ansible.yaml for this purpose instead.
# ******************************************************************************
## A Heat environment file which can be used to set up storage
## backends. Defaults to Ceph used as a backend for Cinder, Glance and
## Nova ephemeral storage.
resource_registry:
  OS::TripleO::Services::CephMgr: /usr/share/openstack-tripleo-heat-templates/docker/services/ceph-ansible/ceph-mgr.yaml
  OS::TripleO::Services::CephMon: /usr/share/openstack-tripleo-heat-templates/docker/services/ceph-ansible/ceph-mon.yaml
  OS::TripleO::Services::CephOSD: /usr/share/openstack-tripleo-heat-templates/docker/services/ceph-ansible/ceph-osd.yaml
  OS::TripleO::Services::CephClient: /usr/share/openstack-tripleo-heat-templates/docker/services/ceph-ansible/ceph-client.yaml

parameter_defaults:
  CinderEnableIscsiBackend: false
  CinderEnableRbdBackend: true
  CinderBackupBackend: ceph
  NovaEnableRbdBackend: true
#  CephAnsibleDisksConfig:
#    devices:
#    - /dev/vdb
#    - /dev/vdc
#    osd_scenario: collocated

  CephAnsiblePlaybookVerbosity: 3

  CephAnsibleDisksConfig:
    devices:
    - /dev/vdb
    - /dev/vdc
    osd_scenario: lvm
    osd_objectstore: bluestore

